
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publisher
    working_dir: /app
    command: python publish.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis", "XLEN", "fitness:users"]
      interval: 2s
      retries: 5
      start_period: 5s

  storage_writer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_writer
    working_dir: /app
    command: python storage_writer.py
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
      publisher:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app
    restart: unless-stopped

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fastapi
  #   working_dir: /app
  #   command: uvicorn llm.app:app --host 0.0.0.0 --port 8000
  #   depends_on:
  #     - redis
  #     - mongo
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - MONGO_URI=mongodb://mongo:27017
  #     - OLLAMA_API=${OLLAMA_API}
  #     - OLLAMA_MODEL=${OLLAMA_MODEL}
  #     - PORT=8000
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   restart: unless-stopped



  # agent:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: agent
  #   working_dir: /app/agent
  #   command: python agent_service.py
  #   depends_on:
  #     - redis
  #     - api
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - RL_MODEL_PATH=models/fitness_agent_ppo.zip
  #   volumes:
  #     - .:/app
  #     - ./agent/models:/app/agent/models
  #   restart: unless-stopped


volumes:
  redis-data:
  mongo-data:
