services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publisher
    working_dir: /app
    command: python publish.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app

  storage_writer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_writer
    working_dir: /app
    command: python storage_writer.py
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app

volumes:
  redis-data:
  mongo-data:
