
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publisher
    working_dir: /app
    command: python publish.py
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis", "XLEN", "fitness:users"]
      interval: 2s
      retries: 5
      start_period: 5s

  storage_writer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_writer
    working_dir: /app
    command: python storage_writer.py
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
      publisher:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: python agent/agent_service.py

volumes:
  redis-data:
  mongo-data:
