version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: publisher
    command: python publish.py
    depends_on:
      - redis

  storage_writer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_writer
    command: python storage_writer.py
    depends_on:
      - redis
      - mongo

volumes:
  redis-data:
  mongo-data:
